# Generated by Django 4.2.3 on 2023-09-26 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user_name',
            new_name='username',
        ),
    ]
