# Generated by Django 4.2.3 on 2023-09-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_delete_login_rename_user_name_signup_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('date', models.DateTimeField(max_length=8, verbose_name='date')),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
