# Generated by Django 4.2.3 on 2023-09-26 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_register_delete_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Signup',
        ),
    ]
