# Generated by Django 4.2.3 on 2023-09-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_rename_register_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='date',
        ),
    ]
