# Generated by Django 4.2.3 on 2023-09-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_remove_signup_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='user_name',
        ),
    ]
