# Generated by Django 4.2.3 on 2023-09-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_rename_username_signup_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
    ]
