# Generated by Django 4.2.3 on 2023-09-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_signup_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='fullname')),
                ('gender', models.CharField(max_length=50, verbose_name='gender')),
                ('age', models.IntegerField(verbose_name='age')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('currentL', models.CharField(max_length=50, verbose_name='clocation')),
                ('occupation', models.CharField(max_length=50, verbose_name='occupation')),
                ('smoking', models.CharField(max_length=50, verbose_name='smoking')),
                ('pets', models.CharField(max_length=50, verbose_name='pets')),
                ('budget', models.IntegerField(verbose_name='budget')),
                ('picture', models.ImageField(upload_to='images/')),
                ('social', models.CharField(max_length=50, verbose_name='social')),
                ('hobbies', models.CharField(max_length=50, verbose_name='hobbies')),
            ],
        ),
    ]
