# Generated by Django 4.2.3 on 2023-09-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hobbies',
        ),
    ]
