# Generated by Django 4.2.3 on 2023-09-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
