# Generated by Django 4.2.3 on 2023-10-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='', max_length=70, verbose_name='description'),
        ),
    ]
