# Generated by Django 4.2.3 on 2023-10-24 13:16

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_rename_sender_connectionrequest_from_user_and_more'),
    ]

    operations = [
        # Remove the previous migration altering the Signup model's email field
        migrations.RemoveField(
            model_name='signup',
            name='email',
        ),

        # Add a ForeignKey relationship between Profile and Signup
        migrations.AddField(
            model_name='profile',
            name='signup',
            field=models.ForeignKey(
                to='mysite.Signup',  # Correct 'to' value
                on_delete=models.CASCADE,
            ),
        ),
    ]
