# Generated by Django 4.2.3 on 2023-10-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_profile_user_alter_signup_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
