# Generated by Django 4.2.3 on 2023-10-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
