# Generated by Django 4.2.3 on 2023-10-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='utsav@gmail.com', max_length=254, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
    ]
