# Generated by Django 4.2.3 on 2023-10-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_remove_profile_user_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='currentL',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='jhapa', max_length=50, verbose_name='location'),
            preserve_default=False,
        ),
    ]
