# Generated by Django 4.2.3 on 2023-10-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_remove_profile_currentl_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='utsav adhikari', max_length=30, verbose_name='username'),
            preserve_default=False,
        ),
    ]
