# Generated by Django 4.2.3 on 2023-10-31 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_remove_profile_full_name_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='user_name',
            new_name='username',
        ),
    ]
