# Generated by Django 4.2.3 on 2023-11-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='currentL',
            field=models.CharField(default='jhapa', max_length=50, verbose_name='currentL'),
            preserve_default=False,
        ),
    ]
