# Generated by Django 4.2.3 on 2023-11-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0030_remove_chatmessage_receiver_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectionRequest',
        ),
    ]
