# Generated by Django 4.2.3 on 2023-11-04 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0032_remove_profile_currentl_profile_latitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
