# Generated by Django 4.2.3 on 2023-11-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0033_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currentL',
            field=models.CharField(default='jhapa', max_length=50, verbose_name='currentL'),
            preserve_default=False,
        ),
    ]
