# Generated by Django 4.2.3 on 2023-11-05 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0034_profile_currentl'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='registration date'),
            preserve_default=False,
        ),
    ]
