# Generated by Django 4.2.3 on 2023-11-09 03:47

from django.db import migrations, models
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0038_alter_profile_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Registered'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to=mysite.models.filepath),
        ),
    ]
